// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivfycgenmahjfiapzexn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZnljZ2VubWFoamZpYXB6ZXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTUyNjcsImV4cCI6MjA3NDI3MTI2N30.jagXHPUMmCb5gCN_sNEuqdcgiHT0XAh8mXrYxpGRlVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});